### ISSUE TITLE
Problems with the instructions 'How to use kiri-docker'

### ISSUE THREAD

**Issue by BenRoe** [leoheck/kiri-docker#1]
Hello,
i am not newbie with docker, but i have problems to get kiri running with docker.

I pulled the image from docker hub with
```bash
docker pull leoheck/kiri:latest
```

To access the program inside the container i normally us a command like this inside my project folder.
```bash
docker run -it -w /kikit -v $(pwd):/kikit yaqwsx/kikit /bin/bash
```

Docker mounts the project folder and has access to the files. Then inside the container i run the program.
Can i use Kiri this way?

Why i don't use the described way.
I add `export PATH="$(pwd)/kiri-docker/"` and get this error.

```
.autocomplete.async.start:13: command not found: true
```
I use `oh-my-zsh` with `zsh-autocomplete.plugin.zsh`

**Comment by BenRoe** [comment]
I have set the path like this
```
export PATH="/Users/ben/git/kiri-docker
```
but if i run `kiri` i get the following errors.

```bash
/Users/ben/Git/kiri-docker/kiri: line 127: basename: command not found
/Users/ben/Git/kiri-docker/kiri: line 139: grep: command not found

| KiRI Docker
| Image: leoheck/kiri
| Container: kiri

/Users/ben/Git/kiri-docker/kiri: line 165: xauth: command not found
/Users/ben/Git/kiri-docker/kiri: line 165: sed: command not found
/Users/ben/Git/kiri-docker/kiri: line 165: xauth: command not found
/Users/ben/Git/kiri-docker/kiri: line 167: setfacl: command not found
/Users/ben/Git/kiri-docker/kiri: line 212: docker: command not found
```

Second problem is that i have a Mac M1 and the images is not working with it.
Kikit create an image with, maybe this helps.
```yml
       - name: "m1"
            suffix: -m1
            platform: linux/arm64/v8
            repo: arm64v8/ubuntu
```

**Comment by leoheck** [comment]
Hi @BenRoe now, this kiri (docker) is a script that I put to run it from my linux (currently Ubuntu 22.10). Depending on the OS, something will need to be improved or changed.

What is the Operating System you using?

Maybe you are using it on Mac (or perhaps Windows, somehow)?

**Comment by leoheck** [comment]
The issue with running it with a simple command like `docker...` is that kiri is a GUI tool since Kicad does not have a command line interface. Then for that, the docker has to be configured to launch the GUI. There are other settings to allow the docker to be accessible from a browser in the host.

**Comment by leoheck** [comment]
> Second problem is that i have a Mac M1 and the images is not working with it.
> Kikit create an image with, maybe this helps.

Ah, I see. you have a mac then. So, I did not try to check how it works there or if it can work.
If you just want to use Kikit, then there is a docker, especially for that (of its creator) and you don't have to use kiri docker. 

But if you want to use it because you also want to use Kiri, then I will have to check how to make this work on MacOS (especially on M1). But I did not try to run this on Mac yet.

**Comment by leoheck** [comment]
But this issue you should not have, right? Docker is missing in your system.

```
/Users/ben/Git/kiri-docker/kiri: line 212: docker: command not found
```

**Comment by leoheck** [comment]
If quartz works on M1, then you could try something like this

```
# install quartz
brew install xquartz
```

```
open -a XQuartz

IP=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')
export DISPLAY=$IP:0

export PATH=/usr/X11/bin/xhost:$PATH
xhost + $IP

docker run \
	-it \
	--rm \
	-e DISPLAY \
	--hostname="kiri" \
	--net=bridge \
	--name ${container_name} \
	--mount type=bind,source="${repo_path}",target="${docker_repo_path}" \
	-v /tmp/.X11-unix:/tmp/.X11-unix
	${container_img} \
	zsh -i -c "${KIRI_SCRIPT}"
```

**Comment by BenRoe** [comment]
Thank you for your help. Since i don't really need the schematic diff, i will try [KiCad-Diff](https://github.com/Gasman2014/KiCad-Diff). 
If i find the time, i will try your suggestion. 
Thx for your help.

**Comment by leoheck** [comment]
Kicad diff is a python script. It will work easier, for sure.

**Comment by topherbuckley** [comment]
This also relates to [this](https://github.com/leoheck/kiri-docker/pull/6) so just commenting to pull attention towards why important. 

> But this issue you should not have, right? Docker is missing in your system.
> 
> ```
> /Users/ben/Git/kiri-docker/kiri: line 212: docker: command not found
> ```

I may or may not have. What definitely happened was the user overwrote their PATH (where access to docker likely normally lies). 

> I have set the path like this
> 
> ```
> export PATH="/Users/ben/git/kiri-docker
> ```
> 
> but if i run `kiri` i get the following errors.
> 
> /Users/ben/Git/kiri-docker/kiri: line 127: basename: command not found
> /Users/ben/Git/kiri-docker/kiri: line 139: grep: command not found
> 
> | KiRI Docker
> | Image: leoheck/kiri
> | Container: kiri
> 
> /Users/ben/Git/kiri-docker/kiri: line 165: xauth: command not found
> /Users/ben/Git/kiri-docker/kiri: line 165: sed: command not found
> /Users/ben/Git/kiri-docker/kiri: line 165: xauth: command not found
> /Users/ben/Git/kiri-docker/kiri: line 167: setfacl: command not found
> /Users/ben/Git/kiri-docker/kiri: line 212: docker: command not found
> 
> Second problem is that i have a Mac M1 and the images is not working with it. Kikit create an image with, maybe this helps.
> 
>        - name: "m1"
>             suffix: -m1
>             platform: linux/arm64/v8
>             repo: arm64v8/ubuntu
