### ISSUE TITLE
Empty webpage (no diff/file view)

### ISSUE THREAD

**Issue by QrackEE** [leoheck/kiri-docker#2]
OS: Ubuntu Mate 22.04.2
Browser: Firefox 113.0.1
Kicad: 6.0.2
kiri-docker image: leoheck/kiri     latest    2d71b85d6d02

I am trying to perform schematic comparison. For purpose of this demonstration I created dummy project with schematics only, with dummy components. After running
`kiri <project absolute path>` 
I could see the webserver running, but nothing more than general GUI layout (no file selection / preview pane, nothing)
![image](https://github.com/leoheck/kiri-docker/assets/8284135/44b6ef79-8dc7-408e-be0c-286f35db9f3f)

Hoping to get some more detail, I looked into the browser Console - and something interesting was there indeed, looking as if kiri-server cannot find / access the files. Listing them from withing docker container is possible though.

When attempting to access via `http://172.17.0.2:8080/_local_/` I get simple list of files:
![image](https://github.com/leoheck/kiri-docker/assets/8284135/38905af9-ad12-42d0-b7a1-25c8ee8af6b3)

Unsurprisingly, when attempting to use URL from the Console there is 404. From picture above already can be seen that there is no _\_KIRI\__ subdirectory and looks that this request is not handled by the server very well.
![image](https://github.com/leoheck/kiri-docker/assets/8284135/32fe8049-274e-4212-a81b-f8ba6c202ba3)

Is that some bug or am I doing something wrong?

Best regards

**Comment by leoheck** [comment]
Hi @QrackEE, are you running it inside the project folder or from outside?
Is your project in the root of the repository or nested in a folder inside of it?

Could you run it one more time inside the project folder with the flags `-V -r` like this:
```bash
kiri PROJECT_REPO_PATH -k -V -r
```

- `-V` is for verbose, so you may see which command is failing. 
- `-r` is to remove the previous run, starting a new one, fresh. 

Alternatively, you could run it like this, then you will be logged inside the docker, with the repo there, where you can run kiri from there directly. Then you can also investigate the files generated inside the `.kiri` folder
```bash
kiri PROJECT_REPO_PATH -d
```


Is it possible to share your project so I can check if it is working outside of the docker?
You can send it to my email if it is not public.

**Comment by leoheck** [comment]
Ah, alternatively, to discard issues with the project. you could test it with this one too.
https://github.com/leoheck/assoc-board

**Comment by leoheck** [comment]
Also, can you show me this the versions used in the kiri-docker, like:
```
kiri-docker took 22.8s …
➜ ./kiri /home/lheck/Documents/KICAD_PROJECTS/assoc-board -k -v   

    kiri 6e27eec 2023/05/17 01h16
    kicad 7.0.2-6a45011f42~172~ubuntu22.04.1
    plotgitsch v0.9.0-8-ge5f94e4
    kidiff 08f26b7 2023/05/17 01h16
```

**Comment by leoheck** [comment]
>     kiri c1e1f38 2023/04/01 03h26

Cool, yesterday I've pushed a new version of the docker after talking with. With the latest changes of Kiri and it is also using Kicad 7.0.2

![image](https://github.com/leoheck/kiri-docker/assets/1277920/9e1b8053-74d1-4432-b9ff-f21827b94dd4)


When you say
```
kiri PROJECT_REPO_PATH -k -V -r
```

You are actually replacing the `PROJECT_REPO_PATH` with the path to your repository, right?
I run it like this (which is going to pass the project to the container automatically.)

```bash
./kiri /home/lheck/Documents/KICAD_PROJECTS/assoc-board -k -V -r
```

> The issue can be considered closed for me, thank you for the tip.

Good. 

> some of which lines (head:, grep:, sed:), unsurprisingly, are also printed in non-verbose mode. 

Ah, this might be an issue since I don't allow kiri to do that. Please, give it a try with the latest docker image I pushed yesterday since it has a Kiri version from May. It may not have this issue.

**Comment by leoheck** [comment]
Hey @QrackEE is this issue solved? If yes, can you close it? If not, what else can I do to help you?

**Comment by QrackEE** [comment]
Hi, yes, of course; thank you for the reminder and sorry for not closing this one earlier :)
